language: objective-c
osx_image: xcode8.3
xcode_project: SlidingPageTabViewController.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: SlidingPageTabViewController
xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=SlidingPageTabViewController
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
skip_cleanup: true
on:
  repo: elliekwon/SlidingPageTabViewController
  tags: true
